const stackData = [
    {
        "title": "How to get state from custom hooks to update in parent component?",
        "description": "I am trying to separate some logic from my component into a custom hook. I feel like i'm misunderstanding some fundamentals but I thought my code would work. I basically update my state in my custom useTrip hook, and i want my map component to have that same updated state.",
        "language1": "javascript",
        "language2": "reactjs",
        "language3": "react-hooks",
        "votes": "3",
        "views": "10",
        "username":"Rahul",

    },
     {
        "title": "RTK Query Pattern for fetching data with query arguments",
        "description": "I have an application where multiple components are fetching data like below and is using the data for some rendering. const {data} = useGetUserQuery({shippingAddressId: 123}); ",
        "language1": "react-redux",
        "language2": "redux-toolkit",
        "language3": "rtk-query",
        "votes": "16",
        "views": "100",
        "username":"Arjun",

    },
     {
        "title": "Enum inside the Array is not validting in json-schema",
        "description": "I am validating the json with json_schema.Allowed values for ghrBillingCode should be only 'I9NOT' expected result should be error as 2nd and 3rd node is not I9NOT but it is validating json as correct.",
        "language1": "jsonschema",
        "language2": "json-schema-validator",
        "language3": "json",
        "votes": "14",
        "views": "50",
        "username":"Martin",

    },
     {
        "title": "How to pass a JSONResponse back to Django Template",
        "description": "I have this custom view function that would be automatically executed when the user violates my login policy (this is done via django-axes). I am unable to display my JSONResponse data on Django template. May I know if there is any workaround on this?",
        "language1": "json",
        "language2": "django",
        "language3": "ajax",
        "votes": "20",
        "views": "120",
        "username":"Albert",

    },
     {
        "title": "Hide div element after a few seconds Angular 7",
        "description": "So I am having trouble understanding how to do this and how to approach this issue... I have a scroll animation on my page and I want to hide that div with animation after 3 seconds when it comes into view.",
        "language1": "html",
        "language2": "angular",
        "language3": "javascript",
        "votes": "5",
        "views": "18",
        "username":"Raman",

    },
]


const companiesData = [{
        "company_name": "Baker Huges",
        "place": "Bengalure; Kochi; Pune",
        "domain": "Software Development/ Engineering",
        "description": "Our employees work on things that matter - reducing the carbon intensity of our operations, applying proven low-carbon technology to help our customers meet their environmental goals, and innovating for the future of energy. Baker Hughes is on a journey to utilize software and digital technology for better outcomes.",
        "language1": ".net",
        "language2": "corestandard",
         "language3": "scrum",
         "logo": "https://i.stack.imgur.com/jbEsE.png?s=128",
    },
    {
        "company_name": "Baeldung",
        "place": "No office location",
        "domain": "eLearning, Software Development, Web Development",
        "description": "Our Editorial Team As an author for Baeldung, you'll work within a team of authors and editors that will provide guidance and feedback on your articles and code. You can check out our team here: editors and authors.",
        "language1": "java",
        "language2": "spring",
        "language3": "linux",
        "logo": "https://i.stack.imgur.com/RiaaM.jpg?s=128",

    },
     {
        "company_name": "Caterpillar Inc.", 
        "place": "Bengaluru; Chennai; Geneva",
        "domain": " Internet of Things, Manufacturing, Software Development / Engineering",
        "description": "Caterpillar is a company of builders. Of problem solvers. Of innovators who want to impact the world. Our people build and design the products and services that help shape the communities where we work and live. We are building on our legacy and innovating for the next generation. One where technology-enabled.",
        "language1": "java",
        "language2": "javascript",
        "language3": "python",
        "logo": "https://i.stack.imgur.com/Wmh9a.png?s=128",

    },
     {
        "company_name": "Stardog Union", 
        "place": "Arlington",
        "domain": " Databases, Enterprise Software, Information Technology",
        "description": "Stardog is the world's leading Knowledge Graph platform for the Enterprise. Turn data into knowledge faster and easier. Stardog lets you query, search, and analyze enterprise data, wherever it is, using scalable, cutting-edge Knowledge Graph technology. Born from an AI research lab at the University of Marylandour.",
        "language1": "java",
        "language2": "jvm",
        "language3": "javascript",
        "logo": "https://i.stack.imgur.com/5DP0L.png?s=128",
    },
      {
        "company_name": "roadsurfer GmbH", 
        "place": "München",
        "domain": "Online Travel, Travel & Tourism, Travel Planning",
        "description": "At roadsurfer we are building up new tech teams to continue the development of our software platform (which we call Wave), and to build new applications and services that will help our customers to get the most from roadsurfer products - whether renting a campervan, booking a private camping spot, or buying a.",
        "language1": "vue.js",
        "language2": "php",
        "language3": "symfony",
        "logo": "https://i.stack.imgur.com/RvxYB.png?s=128",
    },
    {
        "company_name": "Copado Strategic Services", 
        "place": "San Francisco",
        "domain": "Cybersecurity, DevOps, Internet Infrastructure",
        "description": "New Context is a rapidly growing consulting company in the heart of downtown San Francisco. We specialize in Lean Security; an approach that leads organizations to build better software thru hands-on technical and management consulting. We are a group of engineers who live and breath Agile Infrastructure,.",
        "language1": "chef",
        "language2": "puppet",
        "language3": "ansible",
        "logo": "https://i.stack.imgur.com/XTxAK.png?s=128",
    },
]